package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "group_detail")
public class GroupDetailDo {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int id;
  
  // The venue name
  @NotNull
  private String venuename;
  
// latitude
//The venue name
  @NotNull
  private Double latitude;
  
  //longitude
//The venue name
  @NotNull
  private Double longitude;
  
  //departure time
  private String departuretime;
  
//departure time
  private int totalguests;
  
  //notes
  private String notes;
  
  //boolean to indicate whether group deprecated
  private int retired;
  
  //owner of group
  private long ownerid;
  
  
  

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public GroupDetailDo() { }

 

  // Getter and setter methods
  
  public GroupDetailDo(String venuename, String departuretime, int totalguests,
		int retired, long ownerid) {
	  this.venuename = venuename; 
	  this.departuretime = departuretime; 
	  this.totalguests = totalguests;
	  this.retired = retired;
	  this.ownerid = ownerid;
	
}

public GroupDetailDo(int id) {
	this.id = id;
}



	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getVenuename() {
		return venuename;
	}

	public void setVenuename(String venuename) {
		this.venuename = venuename;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getDeparturetime() {
		return departuretime;
	}

	public void setDeparturetime(String departuretime) {
		this.departuretime = departuretime;
	}

	public int getTotalguests() {
		return totalguests;
	}

	public void setTotalguests(int totalguests) {
		this.totalguests = totalguests;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public int getRetired() {
		return retired;
	}

	public void setRetired(int retired) {
		this.retired = retired;
	}

	public long getOwnerid() {
		return ownerid;
	}

	public void setOwnerid(long ownerid) {
		this.ownerid = ownerid;
	}

 
  
} // class User
