package netgloo.models;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "sms_verify")
public class SmsVerifyDo {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int id;
  
  // The venue name
  @NotNull
  private String phoneno;
  
  @NotNull
  private long smscode;
  
  private int resendcount;
  private String deviceid;
  private int verified;
  private Date lastmodified;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public SmsVerifyDo() { }

  
public SmsVerifyDo(String phoneno, long smscode) {
	this.phoneno = phoneno;
	this.smscode = smscode;
}

public int getId() {
	return id;
}

public void setId(int id) {
	this.id = id;
}

public String getPhoneno() {
	return phoneno;
}

public void setPhoneno(String phoneno) {
	this.phoneno = phoneno;
}

public long getSmscode() {
	return smscode;
}

public void setSmscode(long smscode) {
	this.smscode = smscode;
}

public int getResendcount() {
	return resendcount;
}

public void setResendcount(int resendcount) {
	this.resendcount = resendcount;
}

public String getDeviceid() {
	return deviceid;
}

public void setDeviceid(String deviceid) {
	this.deviceid = deviceid;
}

public int getVerified() {
	return verified;
}

public void setVerified(int verified) {
	this.verified = verified;
}

public Date getLastmodified() {
	return lastmodified;
}

public void setLastmodified(Date lastmodified) {
	this.lastmodified = lastmodified;
}
  
} 
